"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Analytics={today:{pageViews:number;uniqueVisitors:number};sevenDays:{pageViews:number;dailyUniqueVisitors:number};thirtyDays:{pageViews:number;dailyUniqueVisitors:number};registrations:number;days:Array<{date:string;pageViews:number;uniqueVisitors:number}>};
export default function AdminPage(){
 const [analytics,setAnalytics]=useState<Analytics|null>(null);
 useEffect(()=>{fetch("/api/admin/analytics",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(setAnalytics).catch(()=>setAnalytics(null))},[]);
 return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/app" className="admin-logo"><img src="/pratikall-logo.png" alt=""/><span>PratikAll<small>YÖNETİM</small></span></Link><nav><button className="active"><i>G</i>Genel Bakış</button><button><i>D</i>Destek Merkezi</button><button><i>G</i>Güvenlik</button></nav><div className="admin-user"><span>PA</span><div><b>Yetkili yönetici</b><small>Korumalı alan</small></div></div></aside><section className="admin-main"><header><div><p>YÖNETİCİ MERKEZİ</p><h1>Genel Bakış</h1></div><Link className="primary-button" href="/app">Uygulamaya dön</Link></header><div className="admin-alert"><span>●</span><p><b>Gizlilik odaklı ziyaret takibi aktif.</b> IP, e-posta ve cihaz bilgisi saklanmadan günlük anonim sayılar ölçülür.</p><button>Canlı</button></div><div className="admin-kpis"><article><span>Bugünkü ziyaretçi</span><strong>{analytics?.today.uniqueVisitors??"—"}</strong><small>{analytics?.today.pageViews??0} sayfa görüntüleme</small></article><article><span>Son 7 gün</span><strong>{analytics?.sevenDays.dailyUniqueVisitors??"—"}</strong><small>{analytics?.sevenDays.pageViews??0} görüntüleme</small></article><article><span>Son 30 gün</span><strong>{analytics?.thirtyDays.dailyUniqueVisitors??"—"}</strong><small>{analytics?.thirtyDays.pageViews??0} görüntüleme</small></article><article><span>Kayıt olanlar</span><strong>{analytics?.registrations??"—"}</strong><small>Toplam kullanıcı hesabı</small></article></div><section className="admin-panel analytics-panel"><div className="admin-panel-head"><div><h2>Son 7 günlük site trafiği</h2><p>Günlük anonim ziyaretçi ve sayfa görüntüleme</p></div></div><div className="analytics-bars">{analytics?.days.length?analytics.days.map(day=>{const max=Math.max(...analytics.days.map(x=>x.pageViews),1);return <div key={day.date}><span>{new Date(`${day.date}T12:00:00`).toLocaleDateString("tr-TR",{weekday:"short"})}</span><i><b style={{height:`${Math.max(8,day.pageViews/max*100)}%`}}/></i><strong>{day.pageViews}</strong><small>{day.uniqueVisitors} kişi</small></div>}):<p className="analytics-empty">Ziyaretler geldikçe grafik burada oluşacak.</p>}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Geri bildirim yönetimi</h2><p>Yeni, inceleniyor ve tamamlandı durumlarıyla takip edilecek.</p></div></div><div className="analytics-empty">Kullanıcı görüşleri kaydedildikçe bu alanda listelenecek.</div></section></section></main>
}
